### PR TITLE
Updated bower instruction

### PR DESCRIPTION
**Pull request by rikusen0335**
Since I have not installed bower in my pc, and this need to use bower

Or, we get
```
Error: Command failed: bower install --production
'bower' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at Object.default_1 [as default] (C:\Users\rikusen\AppData\Roaming\nvm\v14.16.0\node_modules\nodecg-cli\dist\lib\install-bundle-deps.js:50:29)        
    at Command.action (C:\Users\rikusen\AppData\Roaming\nvm\v14.16.0\node_modules\nodecg-cli\dist\commands\install.js:99:34)
    at Command.listener [as _actionHandler] (C:\Users\rikusen\AppData\Roaming\nvm\v14.16.0\node_modules\nodecg-cli\node_modules\commander\index.js:426:31)
    at Command._parseCommand (C:\Users\rikusen\AppData\Roaming\nvm\v14.16.0\node_modules\nodecg-cli\node_modules\commander\index.js:1002:14)
    at Command._dispatchSubcommand (C:\Users\rikusen\AppData\Roaming\nvm\v14.16.0\node_modules\nodecg-cli\node_modules\commander\index.js:953:18)
    at Command._parseCommand (C:\Users\rikusen\AppData\Roaming\nvm\v14.16.0\node_modules\nodecg-cli\node_modules\commander\index.js:970:12)
    at Command.parse (C:\Users\rikusen\AppData\Roaming\nvm\v14.16.0\node_modules\nodecg-cli\node_modules\commander\index.js:801:10)
    at Object.<anonymous> (C:\Users\rikusen\AppData\Roaming\nvm\v14.16.0\node_modules\nodecg-cli\dist\index.js:37:9)
```

### CODE REVIEW

**Comment by rikusen0335** [comment]
It might better to not use bower but it'd take time

**Comment by zoton2** [comment]
Yeah, bower is a bit outdated now but never had a chance to update this bundle.

It wasn't mentioned in the README, I think because when I wrote it, NodeCG needed bower too.

Can merge in in a bit, will double check later.

**Comment by zoton2** [comment]
Sorry for the delay, changed the wording a bit and merging.

**Comment by rikusen0335** [comment]
Thank you so much! I really appreciate it

**Pull request merged**
